In [2]:
# Consider the below code to answer further questions:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)


# Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

In [3]:
list_

['1', '2', '3', '4', '5']

In [4]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [5]:
type(list_)# list_ is a list datatype

list

In [6]:
type(array_list)# array_list is a array datatype with string objects.

numpy.ndarray

# Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [11]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [12]:
for i in array_list:
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [21]:
# Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)


[1 2 3 4 5]


['1', '2', '3', '4', '5']

# Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.

In [22]:
#yes,array_list contains numbers with int datatype,where as list_ contains string objects
print(array_list)
list_

[1 2 3 4 5]


['1', '2', '3', '4', '5']

In [23]:
# Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

# Q4. Write a code to find the following characteristics of variable, num_array:
* (i) shape
* (ii) size

In [25]:
num_array.size# returns the number of elements present

6

In [26]:
num_array.shape# gives the dimension of the array

(2, 3)

# Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy arraycreation function. [Hint: The size of the array will be 9 and the shape will be (3,3).]

In [28]:
np.zeros(3,3)

array([0., 0., 0.])